include_guard(GLOBAL)

# Validate before resolving or building dependencies. Store mode is opt-in and
# never silently changes a requested feature or patches an installed Qt SDK.
function(gameremote_validate_mac_app_store_options)
    file(REMOVE "${CMAKE_BINARY_DIR}/gameremote-mac-app-store-qt.json")
    if(NOT GAMEREMOTE_MAC_APP_STORE)
        return()
    endif()
    if(NOT APPLE OR NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        message(FATAL_ERROR "GAMEREMOTE_MAC_APP_STORE requires a macOS (APPLE/Darwin) target.")
    endif()
    if(NOT CHIAKI_ENABLE_GUI)
        message(FATAL_ERROR "GAMEREMOTE_MAC_APP_STORE requires CHIAKI_ENABLE_GUI=ON so its Qt SDK is verified.")
    endif()
    if(CHIAKI_ENABLE_WEBENGINE)
        message(FATAL_ERROR "GAMEREMOTE_MAC_APP_STORE requires CHIAKI_ENABLE_WEBENGINE=OFF; use the system-browser sign-in flow.")
    endif()
    if(CHIAKI_ENABLE_STEAM_SHORTCUT)
        message(FATAL_ERROR "GAMEREMOTE_MAC_APP_STORE requires CHIAKI_ENABLE_STEAM_SHORTCUT=OFF; external Steam-client writes are unavailable in this variant.")
    endif()
endfunction()

function(_gameremote_store_json_escape value output)
    string(REPLACE "\\" "\\\\" escaped "${value}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    string(REPLACE "\n" "\\n" escaped "${escaped}")
    string(REPLACE "\r" "\\r" escaped "${escaped}")
    string(REPLACE "\t" "\\t" escaped "${escaped}")
    set(${output} "${escaped}" PARENT_SCOPE)
endfunction()

function(gameremote_validate_mac_app_store_qt qt_core_target)
    gameremote_validate_mac_app_store_options()
    if(NOT GAMEREMOTE_MAC_APP_STORE)
        return()
    endif()
    if(NOT TARGET "${qt_core_target}")
        message(FATAL_ERROR "GAMEREMOTE_MAC_APP_STORE cannot verify the selected Qt SDK: target ${qt_core_target} is missing.")
    endif()

    # Inspect only include directories exported by the QtCore target selected by
    # find_package(). A caller-supplied header or a staging flag is not evidence.
    get_target_property(qt_core_include_dirs "${qt_core_target}" INTERFACE_INCLUDE_DIRECTORIES)
    set(qconfig_headers "")
    foreach(include_dir IN LISTS qt_core_include_dirs)
        if(include_dir MATCHES "\\$<")
            message(FATAL_ERROR "GAMEREMOTE_MAC_APP_STORE cannot resolve the selected QtCore include directory at configure time: ${include_dir}")
        endif()
        foreach(relative_header qconfig.h QtCore/qconfig.h Headers/qconfig.h)
            set(candidate "${include_dir}/${relative_header}")
            if(EXISTS "${candidate}" AND NOT IS_DIRECTORY "${candidate}")
                get_filename_component(candidate "${candidate}" REALPATH)
                list(APPEND qconfig_headers "${candidate}")
            endif()
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES qconfig_headers)
    list(LENGTH qconfig_headers qconfig_count)
    if(NOT qconfig_count EQUAL 1)
        message(FATAL_ERROR "GAMEREMOTE_MAC_APP_STORE needs exactly one qconfig.h from selected target ${qt_core_target}; found ${qconfig_count}: ${qconfig_headers}. Select one complete Qt SDK with appstore-compliant enabled.")
    endif()
    list(GET qconfig_headers 0 qconfig_header)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${qconfig_header}")
    file(STRINGS "${qconfig_header}" appstore_directives
        REGEX "^[ \t]*#[ \t]*(define|undef)[ \t]+QT_FEATURE_appstore_compliant([ \t]|$)")
    list(LENGTH appstore_directives appstore_directive_count)
    if(NOT appstore_directive_count EQUAL 1)
        message(FATAL_ERROR "GAMEREMOTE_MAC_APP_STORE found a missing or ambiguous QT_FEATURE_appstore_compliant flag in ${qconfig_header}; expected exactly one definition equal to 1.")
    endif()
    list(GET appstore_directives 0 appstore_directive)
    if(NOT appstore_directive MATCHES "^[ \t]*#[ \t]*define[ \t]+QT_FEATURE_appstore_compliant[ \t]+1[ \t]*(//.*|/\\*.*\\*/[ \t]*)?$")
        message(FATAL_ERROR "GAMEREMOTE_MAC_APP_STORE requires QT_FEATURE_appstore_compliant=1 in the selected Qt SDK, but ${qconfig_header} contains '${appstore_directive}'. Build/select Qt with -feature-appstore-compliant; do not edit its headers.")
    endif()

    # This receipt records a configure-time Qt feature check, not signing,
    # sandbox runtime verification, or App Store approval.
    file(SHA256 "${qconfig_header}" qconfig_sha256)
    _gameremote_store_json_escape("${qconfig_header}" qconfig_json)
    _gameremote_store_json_escape("${qt_core_target}" qt_core_target_json)
    _gameremote_store_json_escape("${Qt6Core_DIR}" qt_core_package_json)
    _gameremote_store_json_escape("${Qt6Core_VERSION}" qt_version_json)
    file(WRITE "${CMAKE_BINARY_DIR}/gameremote-mac-app-store-qt.json"
        "{\n  \"schema_version\": 1,\n  \"scope\": \"configure-time Qt feature check only\",\n  \"qt_core_target\": \"${qt_core_target_json}\",\n  \"qt_core_package_dir\": \"${qt_core_package_json}\",\n  \"qt_version\": \"${qt_version_json}\",\n  \"qconfig_header\": \"${qconfig_json}\",\n  \"qconfig_sha256\": \"${qconfig_sha256}\",\n  \"appstore_compliant\": 1,\n  \"embedded_webengine\": false,\n  \"steam_shortcut\": false\n}\n")
    message(STATUS "Mac App Store Qt feature verified: ${qconfig_header} (SHA256 ${qconfig_sha256})")
endfunction()
